export enum Operation {
    Null = 0,
    Hello = 1,
    HelloAck = 2,
    Transaction = 3,
    Found = 4,
    GetBlock = 5,
    GetIPList = 6,
    SendBL = 7,
    SendIP = 8,
    Busy = 9,
    Nack = 10,
    GetTFile = 11,
    Balance = 12,
    SendBal = 13,
    Resolve = 14,
    GetCBlock = 15,
    MBlock = 16,
    Hash = 17,
    TF = 18,
    Identify = 19
}